### ISSUE TITLE
lsmask() not working

### ISSUE THREAD

**Issue by ishwarmbhat** [irondrummer/pygs#10]
lsmask() function not working. Unable to pick up location of the file. Following is the error:

```
Traceback (most recent call last):

  File "<ipython-input-305-b6a7234e408a>", line 1, in <module>
    runfile('/home/mudraje/workspace/work/cmip5-analysis/codes/final-plots.py', wdir='/home/mudraje/workspace/work/cmip5-analysis/codes')

  File "/home/mudraje/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/mudraje/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/mudraje/workspace/work/cmip5-analysis/codes/final-plots.py", line 75, in <module>
    pr = lsmask(pr, lat, lon, mask = 0)

  File "/home/mudraje/anaconda2/lib/python2.7/site-packages/pygs/gsplots.py", line 292, in lsmask
    f = Dataset(mloc, "r")

  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13231)

IOError: No such file or directory
```

Need to fix file location selection

**Comment by ishwarmbhat** [comment]
Package data not being included in install. Modify setup.py

**Comment by ishwarmbhat** [comment]
Description is wrong. Corresponding integer to mask protects the region from masking in the current implementation. Has to be corrected
